cluster:
  node_count = 4
  name = syzkaller

node:
  ip_port = 7777
  ip_address = 127.0.0.1
  number = 0
  name = node1
  cluster = syzkaller

node:
  ip_port = 7778
  ip_address = 127.0.0.1
  number = 1
  name = node2
  cluster = syzkaller

node:
  ip_port = 7779
  ip_address = 127.0.0.1
  number = 2
  name = node3
  cluster = syzkaller

node:
  ip_port = 7780
  ip_address = 127.0.0.1
  number = 3
  name = node3
  cluster = syzkaller

# mount -t ocfs2 -o cluster_stack=o2cb,cluster_name=syzkaller /dev/loop99 /mnt/test
